all: HW02

HW02:
	g++ -std=c++0x -c Circle.cpp
	g++ -std=c++0x -c Triangle.cpp
	g++ -std=c++0x -c Rectangle.cpp
	g++ -std=c++0x -c ComposedShape.cpp
	g++ -std=c++0x -c main.cpp
	g++ -o HW02 Circle.o Triangle.o Rectangle.o ComposedShape.o main.o
clean:
	rm *.o HW02
