all: HW04

HW04:
	g++ -std=c++0x -c Circle.cpp
	g++ -std=c++0x -c Triangle.cpp
	g++ -std=c++0x -c Rectangle.cpp
	g++ -std=c++0x -c Polygon.cpp
	g++ -std=c++0x -c Polyline.cpp
	g++ -std=c++0x -c ComposedShape.cpp
	g++ -std=c++0x -c main.cpp
	g++ -o HW04 Circle.o Triangle.o Rectangle.o Polygon.o Polyline.o ComposedShape.o main.o
clean:
	rm *.o HW04
